screenLayouts = ["alternateLeft", "verticalDown", "horizontalRight"]
screenStatusBarPos = ["bottom", "bottom", "top"]
padding = 10
margin = 30
barSize = 30
backgroundColor = "1f2430"
foregroundColor = "cbccc6"
accentColor = "ffcc66"
borderColor = "101521"
fontColor = "707a8c"
[[keyShortcuts]]
  cmd = "rofi -show drun"
  inputs = "alt+space"

[[keyShortcuts]]
  cmd = "focusup"
  inputs = "alt+Left"

[[keyShortcuts]]
  cmd = "focusdown"
  inputs = "alt+Right"

[[keyShortcuts]]
  cmd = "moveup"
  inputs = "alt+Left+Shift"

[[keyShortcuts]]
  cmd = "moveDown"
  inputs = "alt+Right+Shift"

[[keyShortcuts]]
  cmd = "nextworkspace"
  inputs = "alt+Up"

[[keyShortcuts]]
  cmd = "lastWorkspace"
  inputs = "alt+Down"

[[keyShortcuts]]
  cmd = "windowToNextWorkspace"
  inputs = "alt+Shift+Up"

[[keyShortcuts]]
  cmd = "windowToPrevWorkspace"
  inputs = "alt+Shift+Down"

[[keyShortcuts]]
  cmd = "close"
  inputs = "alt+q"

[[keyShortcuts]]
  cmd = "flameshot gui"
  inputs = "ctrl+Shift+3"

[[keyShortcuts]]
  cmd = "reloadConfig"
  inputs = "alt+Shift+r"

[[keyShortcuts]]
  cmd = "toggleFloating"
  inputs = "alt+f"

[[keyShortcuts]]
  cmd = "toggleFullscreen"
  inputs = "alt+f+shift"

[[keyShortcuts]]
  cmd = "kitty"
  inputs = "alt+Return"

[[mouseShortcuts]]
  btn = "alt+3"
  event = "resize"

[[mouseShortcuts]]
  btn = "alt+1"
  event = "move"

[[keyShortcuts]]
  cmd = "moveToScreen"
  inputs = "alt+Shift+1"
  screen = 1
[[keyShortcuts]]
  cmd = "moveToScreen"
  inputs = "alt+Shift+2"
  screen = 2

[[keyShortcuts]]
  cmd = "moveToScreen"
  inputs = "alt+Shift+3"
  screen = 3

[[keyShortcuts]]
  cmd = "rofication-gui"
  inputs = "alt+n"
  screen = 3

[[keyShortcuts]]
  cmd = "carouselForward"
  inputs = "alt+z"

[[keyShortcuts]]
  cmd = "carouselBack"
  inputs = "alt+x"

[[keyShortcuts]]
  cmd = "carouselScreenForward"
  inputs = "alt+1"
  screen = 1

[[keyShortcuts]]
  cmd = "carouselScreenForward"
  inputs = "alt+2"
  screen = 2

